import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import stylesPanel from '../styles/Panel.module.css'

const Home: NextPage = () => {
  return (
    <div className={`${styles.intro} ${stylesPanel.panel}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className={styles.intro}>
          <h1>I'm Nathalia Riascos</h1>
          <p>Frontend Developer</p>
        </div>			
			</header>
      {/* <section>
        <div>
          <Image src="/images/me.jpg" alt='prueba' width={100} height={100} />
        </div>
      </section> */}
      
    </div>
  )
}

export default Home
